server:
  port: 8080
spring:
  jpa:
    database: h2
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:bokeunjeong
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
