server:
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://bokeunjeong-postgresql:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
  redis:
    host: bokeunjeong-redis
    port: 6379
