version: "2"

networks:
  default:
    external:
      name: mysql-network

services:
#  mysql:
#    image: mysql
#    container_name: mysql3 # 컨테이너 이름 설정
#    ports:
#      - "9092:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - TZ=Asia/Seoul
#    command:
#      - --character-set-server=utf8mb4
#    volumes:
#      - /Users/bokeun/Dropbox/Programming/docker-volume/mysql:/var/lib/mysql
    oracle:
      image: oracle
      container_name: oracle
      ports:
        - "1521:1521"
      environment:
        - ORACLE_PWD=password
      volumes:
        - /var/lib/docker/volumes/oracle/_data:/ORCL
#        - /var/lib/docker/volumes/oracle/_data:/opt/oracle/oradata
#        - /Users/bokeun/Dropbox/Programming/docker-volume/oracle:/opt/oracle/oradata
